### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by juho** [cloudconvert/cloudconvert-node#27]
https://travis-ci.org/cloudconvert/cloudconvert-node/jobs/314228942

```
> cloudconvert@1.1.2 test /home/travis/build/cloudconvert/cloudconvert-node
> jshint lib tests && node node_modules/.bin/mocha tests/unit
/home/travis/build/cloudconvert/cloudconvert-node/node_modules/mocha/node_modules/supports-color/index.js:2
const os = require('os');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/cloudconvert/cloudconvert-node/node_modules/mocha/lib/reporters/base.js:11:46)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by josiasmontag** [comment]
Time to remove node 0.x tests, I guess.
